### ISSUE TITLE
Any case this could be checked into the JetBrains repository?

### ISSUE THREAD

**Issue by andreycizov** [xmonader/sercapnp#8]
If that's hard - I could do this for you. I have to admit it's simply much easier to sync the plugin on several machines, if it's available publicly.

**Comment by xmonader** [comment]
Hi thanks for your interest, the latest is already pushed https://plugins.jetbrains.com/plugin/9794-sercapnp or did I misread something?

**Comment by andreycizov** [comment]
Right - sorry!

I am using 2019.*. Any particular reason the plugin is constrained to only 2018.*?

To be clear, the output plugin.xml contains this line vs. the one in the  source repo:
  ```<idea-version since-build="182.3911" until-build="182.*"/>```

**Comment by xmonader** [comment]
No particular reason, the last release was done by contributors as I myself only using vscode these days.

**Comment by andreycizov** [comment]
Ah right! Sorry for the spam though - Intellij had auto-added a project file into the folder.

Any case you could mention them?
